"""GitHub OAuth client helpers.

This module owns the backend-only OAuth details: authorization URL creation,
code exchange, authenticated GitHub API calls, and profile normalization. Route
handlers should not need to know GitHub response shapes beyond the normalized
profile returned here.
"""
from __future__ import annotations

import json
import secrets
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timedelta
from typing import Any

import jwt
from jwt import PyJWTError

from app.core.config import settings


GITHUB_AUTHORIZE_URL = "https://github.com/login/oauth/authorize"
GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_API_URL = "https://api.github.com"
GITHUB_OAUTH_SCOPES = ("repo", "read:user", "user:email")


class GitHubOAuthError(Exception):
    """Raised when GitHub OAuth cannot complete safely."""


def create_oauth_state(extension_redirect_url: str | None = None) -> str:
    """Create a short-lived signed OAuth state token.

    The token protects the callback from forged state values and carries the
    optional browser-extension redirect URL without relying on third-party
    cookies.
    """
    if not settings.jwt_secret_key:
        raise GitHubOAuthError("JWT_SECRET_KEY must be configured for OAuth state signing")

    now = datetime.utcnow()
    payload = {
        "typ": "github_oauth_state",
        "nonce": secrets.token_urlsafe(32),
        "iat": now,
        "nbf": now,
        "exp": now + timedelta(minutes=10),
    }
    if extension_redirect_url:
        payload["extension_redirect_url"] = extension_redirect_url

    return jwt.encode(payload, settings.jwt_secret_key, algorithm=settings.jwt_algorithm)


def decode_oauth_state(state: str) -> dict[str, Any]:
    """Validate and decode a signed OAuth state token."""
    if not settings.jwt_secret_key:
        raise GitHubOAuthError("JWT_SECRET_KEY must be configured for OAuth state validation")

    try:
        payload = jwt.decode(
            state,
            settings.jwt_secret_key,
            algorithms=[settings.jwt_algorithm],
            options={"require": ["exp", "iat", "nbf"]},
        )
    except PyJWTError as exc:
        raise GitHubOAuthError("Invalid or expired OAuth state") from exc

    if payload.get("typ") != "github_oauth_state":
        raise GitHubOAuthError("Invalid OAuth state type")
    return payload


def build_github_authorization_url(state: str) -> str:
    """Build the GitHub authorization URL for the OAuth login redirect.

    Args:
        state: Signed CSRF token generated by the backend and validated on callback.

    Returns:
        A GitHub authorization URL that the client can send the browser to.

    Raises:
        GitHubOAuthError: If required OAuth settings are missing.
    """
    if not settings.github_client_id or not settings.github_oauth_callback_url:
        raise GitHubOAuthError("GitHub OAuth is not configured")

    query = urllib.parse.urlencode(
        {
            "client_id": settings.github_client_id,
            "redirect_uri": settings.github_oauth_callback_url,
            "scope": " ".join(GITHUB_OAUTH_SCOPES),
            "state": state,
            "allow_signup": "true",
        }
    )
    return f"{GITHUB_AUTHORIZE_URL}?{query}"


def exchange_code_for_access_token(code: str) -> str:
    """Exchange a GitHub authorization code for a short-lived access token.

    Args:
        code: Authorization code received by the backend callback endpoint.

    Returns:
        GitHub access token used only server-side to fetch the user profile.

    Raises:
        GitHubOAuthError: If GitHub rejects the code or returns malformed data.
    """
    if not settings.github_client_id or not settings.github_client_secret:
        raise GitHubOAuthError("GitHub OAuth client credentials are not configured")

    payload = json.dumps(
        {
            "client_id": settings.github_client_id,
            "client_secret": settings.github_client_secret,
            "code": code,
            "redirect_uri": settings.github_oauth_callback_url,
        }
    ).encode("utf-8")

    response = _request_json(
        GITHUB_TOKEN_URL,
        method="POST",
        body=payload,
        headers={
            "Accept": "application/json",
            "Content-Type": "application/json",
        },
    )

    if "error" in response:
        description = response.get("error_description") or response["error"]
        raise GitHubOAuthError(f"GitHub token exchange failed: {description}")

    access_token = response.get("access_token")
    token_type = str(response.get("token_type", "")).lower()
    if not isinstance(access_token, str) or not access_token or token_type != "bearer":
        raise GitHubOAuthError("GitHub returned an invalid access token response")

    granted_scopes = {
        scope.strip()
        for scope in str(response.get("scope", "")).split(",")
        if scope.strip()
    }
    if "repo" not in granted_scopes:
        raise GitHubOAuthError("GitHub did not grant private repository access")

    return access_token


def fetch_github_user(access_token: str) -> dict[str, Any]:
    """Fetch the authenticated GitHub user's public profile."""
    user = _github_api_get("/user", access_token)
    if not isinstance(user.get("id"), int) or not user.get("login"):
        raise GitHubOAuthError("GitHub returned an incomplete user profile")
    return user


def fetch_github_user_emails(access_token: str) -> list[dict[str, Any]]:
    """Fetch the authenticated GitHub user's email records."""
    emails = _github_api_get("/user/emails", access_token)
    if not isinstance(emails, list):
        raise GitHubOAuthError("GitHub returned an invalid email response")
    return [email for email in emails if isinstance(email, dict)]


def normalize_github_profile(
    profile: dict[str, Any],
    emails: list[dict[str, Any]],
) -> dict[str, Any]:
    """Convert GitHub API payloads into the application user profile shape.

    The selected email is always verified. A primary verified address is
    preferred, then any verified address, then the public profile email if it is
    present and GitHub marked it verified in the email list.
    """
    github_id = profile.get("id")
    login = profile.get("login")
    if not isinstance(github_id, int) or not isinstance(login, str) or not login:
        raise GitHubOAuthError("GitHub profile is missing required identity fields")

    verified_email = _select_verified_email(profile.get("email"), emails)

    return {
        "github_id": github_id,
        "login": login,
        "name": _optional_string(profile.get("name")),
        "email": verified_email,
        "avatar_url": _optional_string(profile.get("avatar_url")),
        "profile_url": _optional_string(profile.get("html_url")),
    }


def _github_api_get(path: str, access_token: str) -> Any:
    return _request_json(
        f"{GITHUB_API_URL}{path}",
        method="GET",
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {access_token}",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )


def _request_json(
    url: str,
    *,
    method: str,
    headers: dict[str, str],
    body: bytes | None = None,
) -> Any:
    request = urllib.request.Request(
        url,
        data=body,
        headers={
            "User-Agent": "code-analytics-platform",
            **headers,
        },
        method=method,
    )

    try:
        with urllib.request.urlopen(  # nosec B310 - URLs are fixed GitHub endpoints.
            request,
            timeout=settings.github_oauth_timeout_seconds,
        ) as response:
            content = response.read()
    except urllib.error.HTTPError as exc:
        detail = _read_error_detail(exc)
        raise GitHubOAuthError(f"GitHub request failed: {detail}") from exc
    except urllib.error.URLError as exc:
        raise GitHubOAuthError("GitHub request could not be completed") from exc
    except TimeoutError as exc:
        raise GitHubOAuthError("GitHub request timed out") from exc

    try:
        return json.loads(content.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise GitHubOAuthError("GitHub returned an invalid JSON response") from exc


def _read_error_detail(exc: urllib.error.HTTPError) -> str:
    try:
        payload = json.loads(exc.read().decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        return f"HTTP {exc.code}"

    message = payload.get("message") or payload.get("error_description")
    if isinstance(message, str) and message:
        return message
    return f"HTTP {exc.code}"


def _select_verified_email(
    public_email: Any,
    emails: list[dict[str, Any]],
) -> str | None:
    primary_verified = _find_email(emails, primary=True)
    if primary_verified:
        return primary_verified

    any_verified = _find_email(emails, primary=False)
    if any_verified:
        return any_verified

    if isinstance(public_email, str) and public_email:
        verified_public = {
            email.get("email")
            for email in emails
            if email.get("verified") is True
        }
        if public_email in verified_public:
            return public_email

    return None


def _find_email(emails: list[dict[str, Any]], *, primary: bool) -> str | None:
    for email in emails:
        address = email.get("email")
        if not isinstance(address, str) or not address:
            continue
        if email.get("verified") is not True:
            continue
        if primary and email.get("primary") is not True:
            continue
        return address
    return None


def _optional_string(value: Any) -> str | None:
    return value if isinstance(value, str) and value else None
